version: '3'

services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
  web:
    build: .
    command: gunicorn -w 2 --access-logfile - --bind 0.0.0.0:8000 --reload Forms.wsgi
    env_file:
      - .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
